default_agent: strands_agent_agentcore_runtime
agents:
  strands_agent_agentcore_runtime:
    name: strands_agent_agentcore_runtime
    entrypoint: /Users/develeap/Desktop/Lior/aws-lambda-calculator-mcp/strands-agent-agentcore-runtime/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: /Users/develeap/Desktop/Lior/aws-lambda-calculator-mcp/strands-agent-agentcore-runtime
    aws:
      execution_role: arn:aws:iam::006262944085:role/strands-agent-agentcore-runtime-role
      execution_role_auto_create: true
      account: 006262944085
      region: us-east-1
      ecr_repository: 006262944085.dkr.ecr.us-east-1.amazonaws.com/strands-agent-agentcore-runtime-ecr
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: strands_agent_agentcore_runtime-H37svwDSIJ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:006262944085:runtime/strands_agent_agentcore_runtime-H37svwDSIJ
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-strands_agent_agentcore_runtime-builder
      execution_role: arn:aws:iam::006262944085:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-655ef5474c
      source_bucket: bedrock-agentcore-codebuild-sources-006262944085-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
